loglevel: disable # 日志级别 info debug disable error fatal warn 等等
debug: true # 调试模式
https: false # https
host: 127.0.0.1 # host 地址
port: 80 # 端口
limit:
  disable: true
  limit: 2 # 每秒允许请求 1 次
  burst: 10 # 最高允许并发
admin: # 管理员账号信息，用于数据填充
  username: username
  rolename: admin
  name: name
  pwd: password
db:
  adapter: sqlite3 # mysql postgres sqlite3
  host: localhost
  port: 3306
  name: goirisapi
  user: root
  password: password
  prefix: blog_
redis:
  host: localhost
  port: 6379
  pwd:
qiniu:
  enable: false
  host: http://your_host
  accesskey: QINIU_ACCESS_KEY
  secretkey: QINIU_SECRET_KEY
  bucket: QINIU_TEST_BUCKET
