version: '2'
services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/init:/docker-entrypoint-initdb.d/
    restart: always
    networks:
      irisadminapi:
        aliases:
          - alias1
    environment:
      MYSQL_DATABASE: goirisadminapi
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      TZ: "Asia/Shanghai"
  irisadminapi:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: irisadminapi
    depends_on:
      - mysql
    volumes:
      - ./backend/config/application.yml:/go/src/github.com/snowlyg/IrisAdminApi/backend/config/application.yml:ro
      - ./logs/:/go/src/github.com/snowlyg/IrisAdminApi/backend/logs/:ro
      - ./resources/app:/go/src/github.com/snowlyg/IrisAdminApi/backend/resources/app/:ro
    ports:
      - 8085:80
    restart: always
    networks:
      irisadminapi:
        aliases:
          - alias1
networks:
  irisadminapi: