version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.18
    steps:
      - checkout
      - run:
          name: Run tests and coverage
          command: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflow:
  version: 2.1
  build-test:
    jobs:
      - build